config/routes.rb
Rails.application.routes.draw do
  get '/book/search', to: 'books#search_form', as: 'search_form'
  get '/book/results', to: 'books#results_search', as: 'search_results'
  put '/book/disable', to: 'books#disable', as: 'book_disable'
  put '/book/enable', to: 'books#enable', as: 'book_enable'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :book
  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/book_api', to: 'api#get_info'
  get '/manage_users', to: 'management_users#manage_users'
  post '/users/change_role', to: 'management_users#change_role', as:'change_role'
  delete '/users/destroy', to: 'management_users#destroy', as:'user_destroy'
  get '/manage_reservations', to: 'management_reservations#manage_reservations'
  get '/my_reservations', to: 'management_reservations#my_reservations'
  get '/reservation', to: 'reservations#book_reservations', as: 'book_reservations'
  post '/reservation', to: 'reservations#create', as:'create_reservation'
  put '/reservation/confirm_loan', to: 'reservations#confirm_loan', as: 'confirm_loan'
  put '/reservation/postpone_return', to: 'reservations#postpone_return', as: 'postpone_return'
  put '/reservation/confirm_return', to: 'reservations#confirm_return', as: 'confirm_return'
  delete '/reservation/delete', to: 'reservations#destroy', as: 'delete_reservation'
  devise_scope :user do
    get '/users/login_email', to: 'login#login_email'
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reservations, :dependent => :delete_all
  validates :title, presence: true
  validates :author, presence: true
  validates :publisher, presence: true
  validates :overview, presence: true
  validates :isbn, presence: true
  validates :released_at, :numericality => { :greater_than_or_equal_to => 0 }, presence: true
  validate :check_length
  after_create :assign_default_values

  def assign_default_values
    self.isDisabled = false
    self.save
  end

  def check_length
    if isbn.nil?
      errors.add(:Isbn, "Can't be left blank") and return
    end
    unless isbn.gsub(" ","").size == 10 or isbn.gsub(" ","").size == 13
      errors.add(:Isbn, "length must be 10 or 13")
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:edit, :update, :destroy]
  before_action :canDelete, only: [:destroy]
  before_action :canChangeDisableStatus, only: [:disable]
  skip_authorize_resource :only => [:search_form,:results_search]
  load_and_authorize_resource
  # GET /books
  # GET /books.json
  def index
    if ApplicationHelper.isAdmin(current_user) or ApplicationHelper.isAdmin(current_user)
      @books = Book.all.sort_by{ |m| m.title.downcase }.paginate(page: params[:page], per_page: 15)
    else
      @books = Book.all.select{|i| !i.isDisabled}.sort_by{ |m| m.title.downcase }.paginate(page: params[:page], per_page: 15)
    end
  end

  def search_form
  end

  def results_search
    title_valid = ApplicationHelper.isValidString(params[:title])
    author_valid = ApplicationHelper.isValidString(params[:author])
    year_valid = true
    if !ApplicationHelper.isValidString(params[:released_at]) or params[:released_at].to_i <0
      year_valid = false
    end

    if ApplicationHelper.isValidString(params[:isbn]) and (params[:isbn].to_s.length==13 or params[:isbn].to_s.length==10)
      if !ApplicationHelper.isOperator(current_user) and !ApplicationHelper.isAdmin(current_user)
        return @books = Array(Book.all.select{|i| i.isbn == params[:isbn].to_s.strip and !i.isDisabled}).paginate(page: params[:page], per_page: 15)
      else
        return @books = Array(Book.all.select{|i| i.isbn == params[:isbn].to_s.strip}.sort_by{ |m| m.title.downcase }).paginate(page: params[:page], per_page: 15)
      end
    elsif title_valid or author_valid or year_valid
        if !ApplicationHelper.isOperator(current_user) and !ApplicationHelper.isAdmin(current_user)
          @search = Book.ransack(title_cont: params[:title], author_cont: params[:author], released_at_eq: params[:released_at], isDisabled_eq: false)
        else
          @search = Book.ransack(title_cont: params[:title], author_cont: params[:author], released_at_eq: params[:released_at])
        end
        return @books = Array(@search.result).sort_by{ |m| m.title.downcase }.paginate(page: params[:page], per_page: 15)
    else
      redirect_back fallback_location: root_path, alert: 'Invalid search request' + title_valid.to_s + author_valid.to_s + year_valid.to_s and return
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    if @book.isDisabled and !ApplicationHelper.isOperator(current_user) and !ApplicationHelper.isAdmin(current_user)
      respond_to do |format|
        format.html { redirect_to books_url, alert: 'Insufficient permissions' }
        format.json { head :no_content }
      end
    end

  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def disable
    @book = Book.find(params[:id])
    if (!@book.isDisabled)
      @book.isDisabled=true
      @book.save
      respond_to do |format|
        format.html { redirect_to @book, notice: 'Book was successfully disabled.' }
        format.json { head :no_content }
      end
      return
    end
    respond_to do |format|
      format.html { redirect_to @book, notice: 'Book was already disabled.' }
      format.json { head :no_content }
    end
  end

  def enable
    @book = Book.find(params[:id])
    if (@book.isDisabled)
      @book.isDisabled=false
      @book.save
      respond_to do |format|
        format.html { redirect_to @book, notice: 'Book was successfully enabled.' }
        format.json { head :no_content }
      end
      return
    end
    respond_to do |format|
      format.html { redirect_to @book, notice: 'Book was already enabled.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :publisher, :overview, :isbn, :created_at, :released_at, :coverlink)
    end

    def canDelete
      if current_user!=nil
        if !current_user.has_role? :admin or !ApplicationHelper.hasValidRole(current_user)
          redirect_to root_path alert: "User not enabled to manage users"
        end
      else
        redirect_to root_path
      end
    end

  def canChangeDisableStatus
    if current_user!=nil
      if (!current_user.has_role? :admin and !current_user.has_role? :operator) or !ApplicationHelper.hasValidRole(current_user)
        redirect_to root_path alert: "User not enabled to manage users"
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def canManageBooks(user)
    if user.has_role? :admin or user.has_role? :operator
      return true
    end
    return false
  end
end

app/views/books/_form.html.erb
<% content_for :for_head do %>
    <script src="https://cdn.jsdelivr.net/npm/kotlin@1.2.51/kotlin.min.js"></script>
    <%= javascript_include_tag '/javascript/books/bookinfo_kotlin.js', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/stylesheets/book.css', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>


<body>
    <div class="container">
      <%= form_with(model: book, local: true, name: "bookForm", id:"myBookForm") do |form| %>
        <% if book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
            <ul>
            <% book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
              <fieldset class="form-fieldset ui-input __first" id="firstForm">
                <%= form.text_field :title, id: 'title' %>
                <label for="title">
                    <span data-text="Title (Required)">Title</span>
                </label>
            </fieldset>

            <fieldset class="form-fieldset ui-input __second">
                <%= form.text_field :author, id: 'author' %>
                <label for="author">
                  <span data-text="Author">Author</span>
                </label>
            </fieldset>


            <fieldset class="form-fieldset ui-input __second">
                <%= form.text_field :publisher, id: 'publisher' %>
                <label for="author">
                  <span data-text="Publisher">Publisher</span>
                </label>
            </fieldset>

            <fieldset class="form-fieldset ui-input __second">
                <%= form.text_field :overview, id: 'overview' %>
                <label for="author">
                  <span data-text="Overview">Overview</span>
                </label>
            </fieldset>

                <fieldset class="form-fieldset ui-input __third">
                <%= form.text_field :isbn, id: 'isbn', onkeypress: 'return event.charCode >= 48 && event.charCode <= 57;', maxlength: 13%>
                <label for="isbn">
                    <span data-text="ISBN">ISBN</span>
                </label>
                <button type="button" class="btn" id="getinfo" onclick=""> Autocomplete </button>
            </fieldset>


                    <fieldset class="form-fieldset ui-input __fourth">
                <%= form.number_field :released_at, min: 0,  id: 'released_at' %>
                <label for="released_at">
                    <span data-text="Release Year" >Release Year</span>
                </label>
            </fieldset>

                    <fieldset class="form-fieldset ui-input __fourth">
                <%= form.text_field :coverlink, id: 'coverlink' %>
                <label for="released_at">
                    <span data-text="Coverlink" >Coverlink</span>
                </label>
            </fieldset>
        <div class="actions">
          <%= form.submit  :class => 'btn', :id => 'search_button'%>
        </div>
      <% end %>

  </div>
</body>

app/views/books/edit.html.erb
<div class="container">
    <h1 style='line-height:48px;'>Editing Book</h1>
</div>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% content_for :for_head do %>
  <%= stylesheet_link_tag '/stylesheets/table.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
<% end %>

<div class="container">
<h1>Books</h1>
<table class="table table-curved">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Isbn</th>
      <th>Release year</th>
      <th>Avaiable</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.isbn %></td>
        <td><%= book.released_at %></td>
        <% if isAvaiable(book) %>
          <td>
            <p style="color:#005407;">
              True
            </p>
          </td>
        <% else %>
          <td>
            <p style="color:#6e0000;">
              False
            </p>
          </td>
        <% end %>
        <td><%= link_to 'Show', book %></td>
        <% if isOperator(current_user) or isAdmin(current_user) %>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <% end %>
        <% if isAdmin(current_user) %>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    <%= will_paginate @books %>
  </tbody>
</table>
<br>
</div>

app/views/books/new.html.erb
<% content_for :for_head do %>
    <%= stylesheet_link_tag '/stylesheets/book.css', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="container">
    <h1 style='line-height:48px;'>New Book</h1>
</div>
<%= render 'form', book: @book %>

app/views/books/results_search.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>

<body>
<div class="container">
  <h1>Search results</h1>

  <table class="table table-hover">
    <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Isbn</th>
      <th>Release year</th>
      <th>Avaiable</th>
    </tr>
    </thead>

    <tbody>
    <% @books.each do |book| %>
    <% if isAvaiable=isAvaiable(book) %>
    <% end %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.isbn %></td>
        <td><%= book.released_at %></td>
        <% if isAvaiable(book) %>
          <td>
            <p style="color:#005407;">
              True
            </p>
          </td>
        <% else %>
          <td>
            <p style="color:#6e0000;">
              False
            </p>
          </td>
        <% end %>
        <td><%= link_to 'Show', book %></td>
      </tr>
    <% end %>
    <%= will_paginate @books %>
    </tbody>
  </table>

  <br>
</div>
      </body>

app/views/books/search_form.erb
<% content_for :for_head do %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <%= javascript_include_tag '/javascript/books/book_search_form.js', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "/stylesheets/book.css", media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<body onload="initializeBookStorage()">
    <div class="container">
        <h1>Find a book</h1>
        <%= form_with url: search_results_url , name: "bookForm", id:"myBookForm", method: :get, :html => { :onsubmit => "return addBookStorage()" }, local: true do |form| %>
            <fieldset class="form-fieldset ui-input __first" id="firstForm">
                <%= form.text_field :title, id: 'title' %>
                <label for="title">
                    <span data-text="Title (Required)">Title</span>
                </label>
            </fieldset>
            <fieldset class="form-fieldset ui-input __second">
                <%= form.text_field :author, id: 'author' %>
                <label for="author">
                  <span data-text="Author">Author</span>
                </label>
            </fieldset>

            <fieldset class="form-fieldset ui-input __third">
                <%= form.text_field :isbn, id: 'isbn', onkeypress: 'return event.charCode >= 48 && event.charCode <= 57;', maxlength: 13%>
                <label for="isbn">
                    <span data-text="ISBN">ISBN</span>
                </label>
            </fieldset>

            <fieldset class="form-fieldset ui-input __fourth">
                <%= form.number_field :released_at, min: 0,  id: 'released_at' %>
                <label for="released_at">
                    <span data-text="Release Year" >Release Year</span>
                </label>
            </fieldset>

        <div class="form-footer">
          <%= form.submit "Search", :class => 'btn', :id => 'search_button', data: { disable_with: false }%>
          <%= submit_tag("Reset", { :name => 'reset', :id => 'reset', :type => 'reset', :class => 'btn', data: { disable_with: false }}) %>
        </div>
        <% end %>
      <div id="bookStorage"></div>
    </div>
</body>

app/views/books/show.html.erb
<% content_for :for_head do %>
    <%= stylesheet_link_tag    '/stylesheets/show.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
<% end %>


<div class="container-grid">

  <div class="header">
    <%= current_user.email%>
  </div>

  <div class="aside">
  <% if @book.coverlink %>
      <%= image_tag(@book.coverlink, :alt => "Book Cover") %>
  <% else %>
    <%= image_tag("https://pre00.deviantart.net/490c/th/pre/i/2016/067/9/c/dead_link_by_lessthanxero-d9ug6qu.jpg", :alt => "Book Cover") %>
  <% end %>
  </div>

  <div class="main">

    <p id="title">
      <%= @book.title %>
    </p>
    <br />
    <p>
      <strong>Written By </strong>
      <%= @book.author %>
    </p>
    </br>
    <p>
      <strong>Publisher:</strong>
      <%= @book.publisher %>
    </p>
    <p>
      <strong>Overview:</strong>
      <%= @book.overview %>
    </p>
    <p>
      <strong>Isbn:</strong>
      <%= @book.isbn %>
    </p>
    <p>
      <strong>Released at:</strong>
      <%= @book.released_at %>
    </p>
  </div>
<div class="footer">
  <%= link_to 'Show reservations and loans',book_reservations_url(:book_id => @book.id), method: :get%>
  <% if isAvaiable(@book) %>
  | <%= link_to "Place reservation",create_reservation_url(:book_id => @book.id, :user_id => current_user.id), method: :post%>
  <% end %>
  <br/>
  <% if isOperator(current_user) or isAdmin(current_user) %>
    <%= link_to 'Edit', edit_book_path(@book) %> |
    <%= link_to 'Back', books_path %> |
  <% if @book.isDisabled %>
    <%= link_to "Enable", {:controller => :books, :action => :enable, :id => @book.id}, :method => :put%>
    <% else %>
    <%= link_to "Disable", {:controller => :books, :action => :disable, :id => @book.id}, :method => :put%>
  <% end %>
  <% end %>
  <% if isAdmin(current_user) %>
    | <%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you REALLY sure?' } %>
  <% end %>
    </div>
</div>