config/routes.rb
Rails.application.routes.draw do
  get '/book/search', to: 'books#search_form', as: 'search_form'
  get '/book/results', to: 'books#results_search', as: 'search_results'
  put '/book/disable', to: 'books#disable', as: 'book_disable'
  put '/book/enable', to: 'books#enable', as: 'book_enable'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :book
  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/book_api', to: 'api#get_info'
  get '/manage_users', to: 'management_users#manage_users'
  post '/users/change_role', to: 'management_users#change_role', as:'change_role'
  delete '/users/destroy', to: 'management_users#destroy', as:'user_destroy'
  get '/manage_reservations', to: 'management_reservations#manage_reservations'
  get '/my_reservations', to: 'management_reservations#my_reservations'
  get '/reservation', to: 'reservations#book_reservations', as: 'book_reservations'
  post '/reservation', to: 'reservations#create', as:'create_reservation'
  put '/reservation/confirm_loan', to: 'reservations#confirm_loan', as: 'confirm_loan'
  put '/reservation/postpone_return', to: 'reservations#postpone_return', as: 'postpone_return'
  put '/reservation/confirm_return', to: 'reservations#confirm_return', as: 'confirm_return'
  delete '/reservation/delete', to: 'reservations#destroy', as: 'delete_reservation'
  devise_scope :user do
    get '/users/login_email', to: 'login#login_email'
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login_email
  end
end

app/helpers/login_helper.rb
module LoginHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/login/login_email.html.erb
<% content_for :for_head do %>
    <%= stylesheet_link_tag '/stylesheets/signup.css', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<%= flash_messages %>

<div class="rectangle">
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
<h2>Login</h2>
  <div class="devise-container">
    <div class="row">
      <div class="form-group">
        <%= f.label :email, class: "labelField"%><br />
        <%= f.email_field :email, autofocus: true, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="form-group">
        <%= f.label :password, class: "labelField"%><br />
        <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="form-group actions">
        <% if devise_mapping.rememberable? -%>
          <div class="field-pull-left">
          <%= f.check_box :remember_me, class:"checkbox" %> 
          <%= f.label :remember_me, {class: "checkbox inline"}  %>
          </div>
        <% end -%>
      </div>
    </div>
  </div>
  <%= f.submit "Log in", class: "login" %>
  </div>
<% end %>