config/routes.rb
Rails.application.routes.draw do
  get '/book/search', to: 'books#search_form', as: 'search_form'
  get '/book/results', to: 'books#results_search', as: 'search_results'
  put '/book/disable', to: 'books#disable', as: 'book_disable'
  put '/book/enable', to: 'books#enable', as: 'book_enable'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :book
  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/book_api', to: 'api#get_info'
  get '/manage_users', to: 'management_users#manage_users'
  post '/users/change_role', to: 'management_users#change_role', as:'change_role'
  delete '/users/destroy', to: 'management_users#destroy', as:'user_destroy'
  get '/manage_reservations', to: 'management_reservations#manage_reservations'
  get '/my_reservations', to: 'management_reservations#my_reservations'
  get '/reservation', to: 'reservations#book_reservations', as: 'book_reservations'
  post '/reservation', to: 'reservations#create', as:'create_reservation'
  put '/reservation/confirm_loan', to: 'reservations#confirm_loan', as: 'confirm_loan'
  put '/reservation/postpone_return', to: 'reservations#postpone_return', as: 'postpone_return'
  put '/reservation/confirm_return', to: 'reservations#confirm_return', as: 'confirm_return'
  delete '/reservation/delete', to: 'reservations#destroy', as: 'delete_reservation'
  devise_scope :user do
    get '/users/login_email', to: 'login#login_email'
  end
end

app/controllers/management_reservations_controller.rb
class ManagementReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :hasValidRole
  before_action :canManage, only: [:manage_reservations]
  def manage_reservations
    @active_reservations = Reservation.all.select{|i| !i.isReturned and i.isLoan}.paginate(page: params[:page], per_page: 15)
    @pending_reservations = Reservation.all.select{|i| !i.isReturned and !i.isLoan}.paginate(page: params[:page], per_page: 15)
    @completed_reservations = Reservation.all.select{|i| i.isReturned and i.isLoan}.paginate(page: params[:page], per_page: 15)
  end


  def my_reservations
    @active_reservations = Reservation.all.select{|i| !i.isReturned and i.isLoan and i.user_id == current_user.id}.paginate(page: params[:page], per_page: 15)
    @pending_reservations = Reservation.all.select{|i| !i.isReturned and !i.isLoan and i.user_id == current_user.id}.paginate(page: params[:page], per_page: 15)
    @completed_reservations = Reservation.all.select{|i| i.isReturned and i.isLoan and i.user_id == current_user.id}.paginate(page: params[:page], per_page: 15)
  end

  def canManage
    if current_user!=nil
      if !current_user.has_role? :admin and !current_user.has_role? :operator
        redirect_to root_path alert: "User not enabled to manage reservations"
      end
    else
      redirect_to root_path
    end
  end

  def hasValidRole
    if current_user!=nil && !ApplicationHelper.hasValidRole(current_user)
      redirect_to root_path alert: "Invalid role detected"
    end
  end
end

app/helpers/management_reservations_helper.rb
module ManagementReservationsHelper
  def getBookById(id)
    return Book.find_by_id(id)
  end

  def nearExpirationDate(date)
    if (date - DateTime.now).to_i <=7
      return true
    end
    return false
  end
end

app/views/management_reservations/manage_reservations.erb
<% content_for :for_head do %>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag '/javascript/manage_users/manage_users.js', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag '/stylesheets/reservations.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag '/stylesheets/table.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script>
    function onLoad() {
      var i, tabcontent, tablinks;
      // Get all elements with class="tabcontent" and hide them
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";

      }

      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      var ls = localStorage.getItem("last_tab")
      if (ls != null) {
        document.getElementById(ls).style.display = "block";
        for (i = 0; i < tablinks.length; i++) {
          if (tablinks[i].value == ls) {
            tablinks[i].className += " active";
            break;
          }
        }
      }

    }

    function openTab(evt, name) {
      // Declare all variables
      var i, tabcontent, tablinks;

      // Get all elements with class="tabcontent" and hide them
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";

      }

      // Get all elements with class="tablinks" and remove the class "active"
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      localStorage.setItem("last_tab", name.toLowerCase());
      // Show the current tab, and add an "active" class to the button that opened the tab
      document.getElementById(name).style.display = "block";
      evt.currentTarget.className += " active";
    }
  </script>
<% end %>


<body onload="onLoad();">
  <div class="container">
    <h1>Manage Reservations/Loans</h1>

    <div class="tab">
      <button class="tablinks" onclick="openTab(event, 'pending')" value="pending">Pending</button>
      <button class="tablinks" onclick="openTab(event, 'active')" value="active">Active</button>
      <button class="tablinks" onclick="openTab(event, 'complete')" value="complete">Complete</button>
    </div>

    <div id="pending" class="tabcontent">
      <h2> Pending reservations:</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Reservation ID</th>
            <th>Email</th>
            <th>Book</th>
            <th>Created at</th>
          </tr>
        </thead>
        <tbody>
          <% @pending_reservations.each do |reservation| %>
            <td>
              <%= reservation.id %>
            </td>
            <td>
              <%= getEmailById(reservation.user_id)%>
            </td>
            <td>
              <%= link_to  getBookById(reservation.book_id).title, getBookById(reservation.book_id) %>
            </td>
            <td>
              <%= reservation.request_date %>
            </td>
            <td>
              <%= button_to 'Confirm Loan', confirm_loan_url, method: :put, data: { confirm: 'Are you sure?' }, params: {id: reservation.id} %>
            </td>
            <% if ApplicationHelper.hasValidRole(current_user) %>
              <td>
                <%= button_to 'Delete reservation', delete_reservation_url, method: :delete, data: { confirm: 'Are you sure?' }, params: {id: reservation.id} %>
              </td>
              <% end %>
                </tr>
                <% end %>
        </tbody>
      </table>
      <%= will_paginate @pending_reservations %>
    </div>


    <div id="active" class="tabcontent">
      <h2> Active loans:</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Loan ID</th>
            <th>Email</th>
            <th>Book</th>
            <th>Created at</th>
            <th>Expire at</th>
            <th>Postponed</th>
          </tr>
        </thead>
        <tbody>
          <% @active_reservations.each do |reservation| %>
            <td>
              <%= reservation.id %>
            </td>
            <td>
              <%= getEmailById(reservation.user_id)%>
            </td>
            <td>
              <%= link_to  getBookById(reservation.book_id).title, getBookById(reservation.book_id) %>
            </td>
            <td>
              <%= reservation.request_date %>
            </td>
            <td><%= reservation.expiration_date %></td>
            <td>
            <%= reservation.isPostponed.to_s.capitalize%>
            </td>

            <td>
              <%= button_to 'Postpone Return', postpone_return_url, method: :put, data: { confirm: 'Are you sure?' }, params: {id: reservation.id} %>
            </td>
            <td>
              <%= button_to 'Confirm Return', confirm_return_url, method: :put, data: { confirm: 'Are you sure?' }, params: {id: reservation.id} %>
            </td>
            <% if isAdmin(current_user) %>
              <td>
                <%= button_to 'Delete reservation', delete_reservation_url, method: :delete, data: { confirm: 'Are you sure?' }, params: {id: reservation.id} %>
              </td>
              <% end %>
                </tr>
                <% end %>
        </tbody>
      </table>
      <%= will_paginate @active_reservations %>
    </div>

    <div id="complete" class="tabcontent">
      <h2> Finished loans:</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Loan ID</th>
            <th>Email</th>
            <th>Book</th>
            <th>Created at</th>
            <th>Expire at</th>
            <th>Returned at</th>
            <th>Postponed</th>
          </tr>
        </thead>
        <tbody>
          <% @completed_reservations.each do |reservation| %>
            <td>
              <%= reservation.id %>
            </td>
            <td>
              <%= getEmailById(reservation.user_id)%>
            </td>
            <td>
              <%= link_to  getBookById(reservation.book_id).title, getBookById(reservation.book_id) %>
            </td>
            <td>
              <%= reservation.request_date %>
            </td>
            <td><%= reservation.expiration_date %></td>
            <td>
              <%= reservation.return_date %>
            </td>
            <td>
              <%= reservation.isPostponed.to_s.capitalize%>
            </td>
            <% if isAdmin(current_user)%>
              <td>
                <%= button_to 'Delete reservation', delete_reservation_url, method: :delete, data: { confirm: 'Are you sure?' }, params: {id: reservation.id} %>
              </td>
              <% end %>
                </tr>
                <% end %>
        </tbody>
      </table>
      <%= will_paginate @completed_reservations %>
    </div>

  </div>
</body>

app/views/management_reservations/my_reservations.erb
<% content_for :for_head do %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
  <%= javascript_include_tag '/javascript/manage_users/manage_users.js', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag '/stylesheets/reservations.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag '/stylesheets/table.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script>
    function onLoad() {
      var i, tabcontent, tablinks;
      // Get all elements with class="tabcontent" and hide them
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      var ls = localStorage.getItem("my_last_tab")
      if (ls != null) {
        document.getElementById(ls).style.display = "block";
        for (i = 0; i < tablinks.length; i++) {
          if (tablinks[i].value == ls) {
            tablinks[i].className += " active";
            break;
          }
        }
      }
    }

    function openTab(evt, name) {
      // Declare all variables
      var i, tabcontent, tablinks;

      // Get all elements with class="tabcontent" and hide them
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
      }
      // Get all elements with class="tablinks" and remove the class "active"
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      localStorage.setItem("my_last_tab", name.toLowerCase());
      // Show the current tab, and add an "active" class to the button that opened the tab
      document.getElementById(name).style.display = "block";
      evt.currentTarget.className += " active";
    }
  </script>
<% end %>

<body onload="onLoad();">
  <div class="container">
    <h1>My Reservations/Loans</h1>

    <div class="tab">
      <button class="tablinks" onclick="openTab(event, 'pending')" value="pending">Pending</button>
      <button class="tablinks" onclick="openTab(event, 'active')" value="active">Active</button>
      <button class="tablinks" onclick="openTab(event, 'complete')" value="complete">Complete</button>
    </div>

    <div id="pending" class="tabcontent">
      <h2> Pending reservations:</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Book</th>
            <th>Created at</th>
          </tr>
        </thead>
        <tbody>
          <% @pending_reservations.each do |reservation| %>
            <td>
              <%= link_to  getBookById(reservation.book_id).title, getBookById(reservation.book_id) %>
            </td>
            <td>
              <%= reservation.request_date %>
            </td>
            <% if ApplicationHelper.hasValidRole(current_user) %>
              <td>
                <%= button_to 'Delete reservation', delete_reservation_url, method: :delete, data: { confirm: 'Are you sure?' }, params: {id: reservation.id} %>
              </td>
              <% end %>
                </tr>
                <% end %>
        </tbody>
      </table>
      <%= will_paginate @pending_reservations %>
    </div>


    <div id="active" class="tabcontent">
      <h2> Active loans:</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Book</th>
            <th>Created at</th>
            <th>Expire at</th>
            <th>Postponed</th>
          </tr>
        </thead>
        <tbody>
          <% @active_reservations.each do |reservation| %>
          <tr>
            <td>
              <%= link_to  getBookById(reservation.book_id).title, getBookById(reservation.book_id) %>
            </td>
            <td>
              <%= reservation.request_date %>
            </td>
            <% if nearExpirationDate(reservation.expiration_date) %>
              <td>
                <p style="color:red;">
                  <%= reservation.expiration_date %>
                </p>
              </td>
            <% else %>
              <td>
                <%= reservation.expiration_date %>
              </td>
            <% end %>
            <td>
              <%= reservation.isPostponed.to_s.capitalize %>
            </td>
            <% if (reservation.expiration_date - DateTime.now).to_i <=7 %>
            <td>
              <%= button_to 'Postpone Return', postpone_return_url, method: :put, data: { confirm: 'Are you sure?' }, params: {id: reservation.id} %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @active_reservations %>
    </div>

    <div id="complete" class="tabcontent">
      <h2> Returned loans:</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Book</th>
            <th>Created at</th>
            <th>Expire at</th>
            <th>Returned at</th>
          </tr>
        </thead>
        <tbody>
          <% @completed_reservations.each do |reservation| %>
            <td>
              <%= link_to  getBookById(reservation.book_id).title, getBookById(reservation.book_id) %>
            </td>
            <td>
              <%= reservation.request_date %>
            </td>

            <td>
              <%= reservation.expiration_date %>
            </td>
            <td>
              <%= reservation.return_date %>
            </td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <%= will_paginate @completed_reservations %>
    </div>
  </div>
</body>