config/routes.rb
Rails.application.routes.draw do
  get '/book/search', to: 'books#search_form', as: 'search_form'
  get '/book/results', to: 'books#results_search', as: 'search_results'
  put '/book/disable', to: 'books#disable', as: 'book_disable'
  put '/book/enable', to: 'books#enable', as: 'book_enable'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :book
  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/book_api', to: 'api#get_info'
  get '/manage_users', to: 'management_users#manage_users'
  post '/users/change_role', to: 'management_users#change_role', as:'change_role'
  delete '/users/destroy', to: 'management_users#destroy', as:'user_destroy'
  get '/manage_reservations', to: 'management_reservations#manage_reservations'
  get '/my_reservations', to: 'management_reservations#my_reservations'
  get '/reservation', to: 'reservations#book_reservations', as: 'book_reservations'
  post '/reservation', to: 'reservations#create', as:'create_reservation'
  put '/reservation/confirm_loan', to: 'reservations#confirm_loan', as: 'confirm_loan'
  put '/reservation/postpone_return', to: 'reservations#postpone_return', as: 'postpone_return'
  put '/reservation/confirm_return', to: 'reservations#confirm_return', as: 'confirm_return'
  delete '/reservation/delete', to: 'reservations#destroy', as: 'delete_reservation'
  devise_scope :user do
    get '/users/login_email', to: 'login#login_email'
  end
end

app/controllers/management_users_controller.rb
class ManagementUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :canManage
  def manage_users
    @users = User.all.paginate(page: params[:page], per_page: 15)
  end

  def change_role
    id = params[:id]
    newrole = params[:changes][:role]
    if !User::ROLES.include?(newrole)
      redirect_to 'manage_users' and return
    end
    user = User.find_by(id: id)
    raise ActiveRecord::RecordNotFound, "Can't find the ActiveRecord for the user" unless !user.nil?
    for role in User::ROLES
      user.remove_role(role.downcase)
    end
    user.add_role(newrole.downcase)
    redirect_to '/manage_users', notice: "Role changed successfully"
  end


  def destroy
    id = params[:id]
    user = User.find_by(id: id)
    raise ActiveRecord::RecordNotFound, "Can't find the ActiveRecord for the user" unless !user.nil?
    user.destroy
    redirect_to '/manage_users', notice: "User deleted successfully"
  end

  def canManage
    if current_user!=nil
      if !current_user.has_role? :admin or !ApplicationHelper.hasValidRole(current_user)
        redirect_to root_path alert: "User not enabled to manage users"
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/management_users_helper.rb
module ManagementUsersHelper
end

app/views/management_users/manage_users.erb
<% content_for :for_head do %>
  <%= javascript_include_tag '/javascript/manage_users/manage_users.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag '/stylesheets/table.css', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>


<body onload="manageUsersLoad();">
  <div class="container">
    <h1>Manage Users</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Email</th>
          <th>Role</th>
          <th>Created at</th>
          <th>Last sign in</th>
          <th>Last IP</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <td>
            <%= user.email %>
          </td>
          <td>
            <%= getRole(user) %>
          </td>
          <td>
            <%= user.created_at %>
          </td>
          <td>
            <%= user.last_sign_in_at %>
          </td>
          <td>
            <%= user.last_sign_in_ip %>
          </td>
          <td>
            <%= form_for :changes, :url => {:action => "change_role",:id => user.id} do |f|%>
              <%= f.select :role, options_for_select(User::ROLES) ,{}, { :class => 'select' }  %>
                <%= f.submit "Change",  :disable_with => "Changing...", :class => 'change' %>
                  <% end %>
          </td>
          <td><%= button_to 'Delete', user_destroy_url, method: :delete, data: { confirm: 'Are you sure?' }, params: {id: user.id} %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
    <%= will_paginate @users %>
  </div>
</body>